/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ChatRouteImport } from './routes/_chat'
import { Route as ChatIndexRouteImport } from './routes/_chat.index'
import { Route as SettingsGeneralRouteImport } from './routes/settings.general'
import { Route as SettingsConnectionsRouteImport } from './routes/settings.connections'
import { Route as SettingsArchivedRouteImport } from './routes/settings.archived'
import { Route as ChatStackRouteImport } from './routes/_chat.stack'
import { Route as ChatModelsRouteImport } from './routes/_chat.models'
import { Route as ChatHomeRouteImport } from './routes/_chat.home'
import { Route as ChatDeployRouteImport } from './routes/_chat.deploy'
import { Route as ChatConfigRouteImport } from './routes/_chat.config'
import { Route as ChatCodeRouteImport } from './routes/_chat.code'
import { Route as ChatAgentsRouteImport } from './routes/_chat.agents'
import { Route as ChatCodeIndexRouteImport } from './routes/_chat.code.index'
import { Route as ChatCodeDraftDraftIdRouteImport } from './routes/_chat.code.draft.$draftId'
import { Route as ChatCodeEnvironmentIdThreadIdRouteImport } from './routes/_chat.code.$environmentId.$threadId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsConnectionsRoute = SettingsConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsArchivedRoute = SettingsArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => SettingsRoute,
} as any)
const ChatStackRoute = ChatStackRouteImport.update({
  id: '/stack',
  path: '/stack',
  getParentRoute: () => ChatRoute,
} as any)
const ChatModelsRoute = ChatModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => ChatRoute,
} as any)
const ChatHomeRoute = ChatHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => ChatRoute,
} as any)
const ChatDeployRoute = ChatDeployRouteImport.update({
  id: '/deploy',
  path: '/deploy',
  getParentRoute: () => ChatRoute,
} as any)
const ChatConfigRoute = ChatConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => ChatRoute,
} as any)
const ChatCodeRoute = ChatCodeRouteImport.update({
  id: '/code',
  path: '/code',
  getParentRoute: () => ChatRoute,
} as any)
const ChatAgentsRoute = ChatAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => ChatRoute,
} as any)
const ChatCodeIndexRoute = ChatCodeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatCodeRoute,
} as any)
const ChatCodeDraftDraftIdRoute = ChatCodeDraftDraftIdRouteImport.update({
  id: '/draft/$draftId',
  path: '/draft/$draftId',
  getParentRoute: () => ChatCodeRoute,
} as any)
const ChatCodeEnvironmentIdThreadIdRoute =
  ChatCodeEnvironmentIdThreadIdRouteImport.update({
    id: '/$environmentId/$threadId',
    path: '/$environmentId/$threadId',
    getParentRoute: () => ChatCodeRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatIndexRoute
  '/settings': typeof SettingsRouteWithChildren
  '/agents': typeof ChatAgentsRoute
  '/code': typeof ChatCodeRouteWithChildren
  '/config': typeof ChatConfigRoute
  '/deploy': typeof ChatDeployRoute
  '/home': typeof ChatHomeRoute
  '/models': typeof ChatModelsRoute
  '/stack': typeof ChatStackRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/code/': typeof ChatCodeIndexRoute
  '/code/$environmentId/$threadId': typeof ChatCodeEnvironmentIdThreadIdRoute
  '/code/draft/$draftId': typeof ChatCodeDraftDraftIdRoute
}
export interface FileRoutesByTo {
  '/settings': typeof SettingsRouteWithChildren
  '/agents': typeof ChatAgentsRoute
  '/config': typeof ChatConfigRoute
  '/deploy': typeof ChatDeployRoute
  '/home': typeof ChatHomeRoute
  '/models': typeof ChatModelsRoute
  '/stack': typeof ChatStackRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/': typeof ChatIndexRoute
  '/code': typeof ChatCodeIndexRoute
  '/code/$environmentId/$threadId': typeof ChatCodeEnvironmentIdThreadIdRoute
  '/code/draft/$draftId': typeof ChatCodeDraftDraftIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat': typeof ChatRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/_chat/agents': typeof ChatAgentsRoute
  '/_chat/code': typeof ChatCodeRouteWithChildren
  '/_chat/config': typeof ChatConfigRoute
  '/_chat/deploy': typeof ChatDeployRoute
  '/_chat/home': typeof ChatHomeRoute
  '/_chat/models': typeof ChatModelsRoute
  '/_chat/stack': typeof ChatStackRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/_chat/': typeof ChatIndexRoute
  '/_chat/code/': typeof ChatCodeIndexRoute
  '/_chat/code/$environmentId/$threadId': typeof ChatCodeEnvironmentIdThreadIdRoute
  '/_chat/code/draft/$draftId': typeof ChatCodeDraftDraftIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/agents'
    | '/code'
    | '/config'
    | '/deploy'
    | '/home'
    | '/models'
    | '/stack'
    | '/settings/archived'
    | '/settings/connections'
    | '/settings/general'
    | '/code/'
    | '/code/$environmentId/$threadId'
    | '/code/draft/$draftId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/settings'
    | '/agents'
    | '/config'
    | '/deploy'
    | '/home'
    | '/models'
    | '/stack'
    | '/settings/archived'
    | '/settings/connections'
    | '/settings/general'
    | '/'
    | '/code'
    | '/code/$environmentId/$threadId'
    | '/code/draft/$draftId'
  id:
    | '__root__'
    | '/_chat'
    | '/settings'
    | '/_chat/agents'
    | '/_chat/code'
    | '/_chat/config'
    | '/_chat/deploy'
    | '/_chat/home'
    | '/_chat/models'
    | '/_chat/stack'
    | '/settings/archived'
    | '/settings/connections'
    | '/settings/general'
    | '/_chat/'
    | '/_chat/code/'
    | '/_chat/code/$environmentId/$threadId'
    | '/_chat/code/draft/$draftId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/connections': {
      id: '/settings/connections'
      path: '/connections'
      fullPath: '/settings/connections'
      preLoaderRoute: typeof SettingsConnectionsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/archived': {
      id: '/settings/archived'
      path: '/archived'
      fullPath: '/settings/archived'
      preLoaderRoute: typeof SettingsArchivedRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_chat/stack': {
      id: '/_chat/stack'
      path: '/stack'
      fullPath: '/stack'
      preLoaderRoute: typeof ChatStackRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/models': {
      id: '/_chat/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ChatModelsRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/home': {
      id: '/_chat/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof ChatHomeRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/deploy': {
      id: '/_chat/deploy'
      path: '/deploy'
      fullPath: '/deploy'
      preLoaderRoute: typeof ChatDeployRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/config': {
      id: '/_chat/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ChatConfigRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/code': {
      id: '/_chat/code'
      path: '/code'
      fullPath: '/code'
      preLoaderRoute: typeof ChatCodeRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/agents': {
      id: '/_chat/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof ChatAgentsRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/code/': {
      id: '/_chat/code/'
      path: '/'
      fullPath: '/code/'
      preLoaderRoute: typeof ChatCodeIndexRouteImport
      parentRoute: typeof ChatCodeRoute
    }
    '/_chat/code/draft/$draftId': {
      id: '/_chat/code/draft/$draftId'
      path: '/draft/$draftId'
      fullPath: '/code/draft/$draftId'
      preLoaderRoute: typeof ChatCodeDraftDraftIdRouteImport
      parentRoute: typeof ChatCodeRoute
    }
    '/_chat/code/$environmentId/$threadId': {
      id: '/_chat/code/$environmentId/$threadId'
      path: '/$environmentId/$threadId'
      fullPath: '/code/$environmentId/$threadId'
      preLoaderRoute: typeof ChatCodeEnvironmentIdThreadIdRouteImport
      parentRoute: typeof ChatCodeRoute
    }
  }
}

interface ChatCodeRouteChildren {
  ChatCodeIndexRoute: typeof ChatCodeIndexRoute
  ChatCodeEnvironmentIdThreadIdRoute: typeof ChatCodeEnvironmentIdThreadIdRoute
  ChatCodeDraftDraftIdRoute: typeof ChatCodeDraftDraftIdRoute
}

const ChatCodeRouteChildren: ChatCodeRouteChildren = {
  ChatCodeIndexRoute: ChatCodeIndexRoute,
  ChatCodeEnvironmentIdThreadIdRoute: ChatCodeEnvironmentIdThreadIdRoute,
  ChatCodeDraftDraftIdRoute: ChatCodeDraftDraftIdRoute,
}

const ChatCodeRouteWithChildren = ChatCodeRoute._addFileChildren(
  ChatCodeRouteChildren,
)

interface ChatRouteChildren {
  ChatAgentsRoute: typeof ChatAgentsRoute
  ChatCodeRoute: typeof ChatCodeRouteWithChildren
  ChatConfigRoute: typeof ChatConfigRoute
  ChatDeployRoute: typeof ChatDeployRoute
  ChatHomeRoute: typeof ChatHomeRoute
  ChatModelsRoute: typeof ChatModelsRoute
  ChatStackRoute: typeof ChatStackRoute
  ChatIndexRoute: typeof ChatIndexRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatAgentsRoute: ChatAgentsRoute,
  ChatCodeRoute: ChatCodeRouteWithChildren,
  ChatConfigRoute: ChatConfigRoute,
  ChatDeployRoute: ChatDeployRoute,
  ChatHomeRoute: ChatHomeRoute,
  ChatModelsRoute: ChatModelsRoute,
  ChatStackRoute: ChatStackRoute,
  ChatIndexRoute: ChatIndexRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface SettingsRouteChildren {
  SettingsArchivedRoute: typeof SettingsArchivedRoute
  SettingsConnectionsRoute: typeof SettingsConnectionsRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsArchivedRoute: SettingsArchivedRoute,
  SettingsConnectionsRoute: SettingsConnectionsRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
