/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PairRouteImport } from './routes/pair'
import { Route as ChatRouteImport } from './routes/_chat'
import { Route as ChatIndexRouteImport } from './routes/_chat.index'
import { Route as SettingsGeneralRouteImport } from './routes/settings.general'
import { Route as SettingsConnectionsRouteImport } from './routes/settings.connections'
import { Route as SettingsArchivedRouteImport } from './routes/settings.archived'
import { Route as ChatStackRouteImport } from './routes/_chat.stack'
import { Route as ChatSessionsRouteImport } from './routes/_chat.sessions'
import { Route as ChatModelsRouteImport } from './routes/_chat.models'
import { Route as ChatHomeRouteImport } from './routes/_chat.home'
import { Route as ChatDeployRouteImport } from './routes/_chat.deploy'
import { Route as ChatConfigRouteImport } from './routes/_chat.config'
import { Route as ChatAgentsRouteImport } from './routes/_chat.agents'
import { Route as ChatSessionsIndexRouteImport } from './routes/_chat.sessions.index'
import { Route as ChatSessionsDraftDraftIdRouteImport } from './routes/_chat.sessions.draft.$draftId'
import { Route as ChatSessionsEnvironmentIdThreadIdRouteImport } from './routes/_chat.sessions.$environmentId.$threadId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PairRoute = PairRouteImport.update({
  id: '/pair',
  path: '/pair',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsConnectionsRoute = SettingsConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsArchivedRoute = SettingsArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => SettingsRoute,
} as any)
const ChatStackRoute = ChatStackRouteImport.update({
  id: '/stack',
  path: '/stack',
  getParentRoute: () => ChatRoute,
} as any)
const ChatSessionsRoute = ChatSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => ChatRoute,
} as any)
const ChatModelsRoute = ChatModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => ChatRoute,
} as any)
const ChatHomeRoute = ChatHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => ChatRoute,
} as any)
const ChatDeployRoute = ChatDeployRouteImport.update({
  id: '/deploy',
  path: '/deploy',
  getParentRoute: () => ChatRoute,
} as any)
const ChatConfigRoute = ChatConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => ChatRoute,
} as any)
const ChatAgentsRoute = ChatAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => ChatRoute,
} as any)
const ChatSessionsIndexRoute = ChatSessionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatSessionsRoute,
} as any)
const ChatSessionsDraftDraftIdRoute =
  ChatSessionsDraftDraftIdRouteImport.update({
    id: '/draft/$draftId',
    path: '/draft/$draftId',
    getParentRoute: () => ChatSessionsRoute,
  } as any)
const ChatSessionsEnvironmentIdThreadIdRoute =
  ChatSessionsEnvironmentIdThreadIdRouteImport.update({
    id: '/$environmentId/$threadId',
    path: '/$environmentId/$threadId',
    getParentRoute: () => ChatSessionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatIndexRoute
  '/pair': typeof PairRoute
  '/settings': typeof SettingsRouteWithChildren
  '/agents': typeof ChatAgentsRoute
  '/config': typeof ChatConfigRoute
  '/deploy': typeof ChatDeployRoute
  '/home': typeof ChatHomeRoute
  '/models': typeof ChatModelsRoute
  '/sessions': typeof ChatSessionsRouteWithChildren
  '/stack': typeof ChatStackRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/sessions/': typeof ChatSessionsIndexRoute
  '/sessions/$environmentId/$threadId': typeof ChatSessionsEnvironmentIdThreadIdRoute
  '/sessions/draft/$draftId': typeof ChatSessionsDraftDraftIdRoute
}
export interface FileRoutesByTo {
  '/pair': typeof PairRoute
  '/settings': typeof SettingsRouteWithChildren
  '/agents': typeof ChatAgentsRoute
  '/config': typeof ChatConfigRoute
  '/deploy': typeof ChatDeployRoute
  '/home': typeof ChatHomeRoute
  '/models': typeof ChatModelsRoute
  '/stack': typeof ChatStackRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/': typeof ChatIndexRoute
  '/sessions': typeof ChatSessionsIndexRoute
  '/sessions/$environmentId/$threadId': typeof ChatSessionsEnvironmentIdThreadIdRoute
  '/sessions/draft/$draftId': typeof ChatSessionsDraftDraftIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat': typeof ChatRouteWithChildren
  '/pair': typeof PairRoute
  '/settings': typeof SettingsRouteWithChildren
  '/_chat/agents': typeof ChatAgentsRoute
  '/_chat/config': typeof ChatConfigRoute
  '/_chat/deploy': typeof ChatDeployRoute
  '/_chat/home': typeof ChatHomeRoute
  '/_chat/models': typeof ChatModelsRoute
  '/_chat/sessions': typeof ChatSessionsRouteWithChildren
  '/_chat/stack': typeof ChatStackRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/_chat/': typeof ChatIndexRoute
  '/_chat/sessions/': typeof ChatSessionsIndexRoute
  '/_chat/sessions/$environmentId/$threadId': typeof ChatSessionsEnvironmentIdThreadIdRoute
  '/_chat/sessions/draft/$draftId': typeof ChatSessionsDraftDraftIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pair'
    | '/settings'
    | '/agents'
    | '/config'
    | '/deploy'
    | '/home'
    | '/models'
    | '/sessions'
    | '/stack'
    | '/settings/archived'
    | '/settings/connections'
    | '/settings/general'
    | '/sessions/'
    | '/sessions/$environmentId/$threadId'
    | '/sessions/draft/$draftId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/pair'
    | '/settings'
    | '/agents'
    | '/config'
    | '/deploy'
    | '/home'
    | '/models'
    | '/stack'
    | '/settings/archived'
    | '/settings/connections'
    | '/settings/general'
    | '/'
    | '/sessions'
    | '/sessions/$environmentId/$threadId'
    | '/sessions/draft/$draftId'
  id:
    | '__root__'
    | '/_chat'
    | '/pair'
    | '/settings'
    | '/_chat/agents'
    | '/_chat/config'
    | '/_chat/deploy'
    | '/_chat/home'
    | '/_chat/models'
    | '/_chat/sessions'
    | '/_chat/stack'
    | '/settings/archived'
    | '/settings/connections'
    | '/settings/general'
    | '/_chat/'
    | '/_chat/sessions/'
    | '/_chat/sessions/$environmentId/$threadId'
    | '/_chat/sessions/draft/$draftId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRouteWithChildren
  PairRoute: typeof PairRoute
  SettingsRoute: typeof SettingsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pair': {
      id: '/pair'
      path: '/pair'
      fullPath: '/pair'
      preLoaderRoute: typeof PairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/connections': {
      id: '/settings/connections'
      path: '/connections'
      fullPath: '/settings/connections'
      preLoaderRoute: typeof SettingsConnectionsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/archived': {
      id: '/settings/archived'
      path: '/archived'
      fullPath: '/settings/archived'
      preLoaderRoute: typeof SettingsArchivedRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_chat/stack': {
      id: '/_chat/stack'
      path: '/stack'
      fullPath: '/stack'
      preLoaderRoute: typeof ChatStackRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/sessions': {
      id: '/_chat/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof ChatSessionsRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/models': {
      id: '/_chat/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ChatModelsRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/home': {
      id: '/_chat/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof ChatHomeRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/deploy': {
      id: '/_chat/deploy'
      path: '/deploy'
      fullPath: '/deploy'
      preLoaderRoute: typeof ChatDeployRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/config': {
      id: '/_chat/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ChatConfigRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/agents': {
      id: '/_chat/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof ChatAgentsRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/sessions/': {
      id: '/_chat/sessions/'
      path: '/'
      fullPath: '/sessions/'
      preLoaderRoute: typeof ChatSessionsIndexRouteImport
      parentRoute: typeof ChatSessionsRoute
    }
    '/_chat/sessions/draft/$draftId': {
      id: '/_chat/sessions/draft/$draftId'
      path: '/draft/$draftId'
      fullPath: '/sessions/draft/$draftId'
      preLoaderRoute: typeof ChatSessionsDraftDraftIdRouteImport
      parentRoute: typeof ChatSessionsRoute
    }
    '/_chat/sessions/$environmentId/$threadId': {
      id: '/_chat/sessions/$environmentId/$threadId'
      path: '/$environmentId/$threadId'
      fullPath: '/sessions/$environmentId/$threadId'
      preLoaderRoute: typeof ChatSessionsEnvironmentIdThreadIdRouteImport
      parentRoute: typeof ChatSessionsRoute
    }
  }
}

interface ChatSessionsRouteChildren {
  ChatSessionsIndexRoute: typeof ChatSessionsIndexRoute
  ChatSessionsEnvironmentIdThreadIdRoute: typeof ChatSessionsEnvironmentIdThreadIdRoute
  ChatSessionsDraftDraftIdRoute: typeof ChatSessionsDraftDraftIdRoute
}

const ChatSessionsRouteChildren: ChatSessionsRouteChildren = {
  ChatSessionsIndexRoute: ChatSessionsIndexRoute,
  ChatSessionsEnvironmentIdThreadIdRoute:
    ChatSessionsEnvironmentIdThreadIdRoute,
  ChatSessionsDraftDraftIdRoute: ChatSessionsDraftDraftIdRoute,
}

const ChatSessionsRouteWithChildren = ChatSessionsRoute._addFileChildren(
  ChatSessionsRouteChildren,
)

interface ChatRouteChildren {
  ChatAgentsRoute: typeof ChatAgentsRoute
  ChatConfigRoute: typeof ChatConfigRoute
  ChatDeployRoute: typeof ChatDeployRoute
  ChatHomeRoute: typeof ChatHomeRoute
  ChatModelsRoute: typeof ChatModelsRoute
  ChatSessionsRoute: typeof ChatSessionsRouteWithChildren
  ChatStackRoute: typeof ChatStackRoute
  ChatIndexRoute: typeof ChatIndexRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatAgentsRoute: ChatAgentsRoute,
  ChatConfigRoute: ChatConfigRoute,
  ChatDeployRoute: ChatDeployRoute,
  ChatHomeRoute: ChatHomeRoute,
  ChatModelsRoute: ChatModelsRoute,
  ChatSessionsRoute: ChatSessionsRouteWithChildren,
  ChatStackRoute: ChatStackRoute,
  ChatIndexRoute: ChatIndexRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface SettingsRouteChildren {
  SettingsArchivedRoute: typeof SettingsArchivedRoute
  SettingsConnectionsRoute: typeof SettingsConnectionsRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsArchivedRoute: SettingsArchivedRoute,
  SettingsConnectionsRoute: SettingsConnectionsRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRouteWithChildren,
  PairRoute: PairRoute,
  SettingsRoute: SettingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
